volumes:
  code_review_pip_local_postgres_data: { }
  code_review_pip_local_postgres_data_backups: { }
  code_review_pip_odoo-web-data: { }
  code_review_pip_odoo-db-data: { }
  code_review_pip_local_redis_data: { }

services:
  django: &django
    build:
      context: .
      dockerfile: compose/pip/local/django/Dockerfile
    image: code_review_pip_local_django
    container_name: code_review_pip_local_django
    # user: "1000:1000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: compose/pip/production/postgres/Dockerfile
    image: code_review_pip_production_postgres
    container_name: code_review_pip_local_postgres
    volumes:
      - code_review_pip_local_postgres_data:/var/lib/postgresql/data
      - code_review_pip_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'

  redis:
    image: docker.io/redis:6
    container_name: code_review_pip_local_redis

    volumes:
      - code_review_pip_local_redis_data:/data

  celeryworker:
    <<: *django
    image: code_review_pip_local_celeryworker
    container_name: code_review_pip_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: code_review_pip_local_celerybeat
    container_name: code_review_pip_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-celerybeat

  flower:
    <<: *django
    image: code_review_pip_local_flower
    container_name: code_review_pip_local_flower
    ports:
      - '5555:5555'
    command: /start-flower


  odoo:
    build:
      context: .
      dockerfile: compose/pip/local/odoo/Dockerfile
    image: code_review_pip_odoo
    container_name: code_review_pip_odoo
    platform: linux/amd64
    env_file:
      - ./.envs/.local/.postgres
    depends_on:
      - postgres
    ports:
      - '8879:8069'
      - '8888:3001'
    volumes:
      - code_review_pip_odoo-web-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
